In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi = np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi = baskaDizi[4:9]

In [12]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingDizisi[:] = 700

In [15]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [16]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [17]:
ornekDizi = np.arange(0,24)

In [18]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
ornekDiziKopyasi = ornekDizi.copy()

In [20]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [23]:
ornekDiziKopyaSlicing[:] = 800

In [24]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [25]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [27]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [28]:
benimMatrixDizim = np.array(benimListem)

In [29]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [30]:
benimMatrixDizim[0]

array([10, 20, 30])

In [31]:
benimMatrixDizim[1][2]

40

In [32]:
benimMatrixDizim[1,2]

40

In [33]:
benimMatrixDizim[2:,2:]

array([[60]])

In [34]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [35]:
yeniMatrix = np.array(yeniListe)

In [36]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [38]:
yeniBirDizi = np.random.randint(1,100,20)

In [39]:
yeniBirDizi

array([73,  3, 95, 18, 44, 26, 93, 10,  3,  2,  9, 49, 84, 35, 15, 49, 25,
       55, 20, 39])

In [40]:
yeniBirDizi > 24

array([ True, False,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [41]:
yeniBirDizi

array([73,  3, 95, 18, 44, 26, 93, 10,  3,  2,  9, 49, 84, 35, 15, 49, 25,
       55, 20, 39])

In [42]:
sonucDizisi = yeniBirDizi > 24

In [43]:
sonucDizisi

array([ True, False,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [44]:
yeniBirDizi

array([73,  3, 95, 18, 44, 26, 93, 10,  3,  2,  9, 49, 84, 35, 15, 49, 25,
       55, 20, 39])

In [45]:
yeniBirDizi[sonucDizisi]

array([73, 95, 44, 26, 93, 49, 84, 35, 49, 25, 55, 39])

In [46]:
yeniBirDizi

array([73,  3, 95, 18, 44, 26, 93, 10,  3,  2,  9, 49, 84, 35, 15, 49, 25,
       55, 20, 39])

In [47]:
yeniBirDizi[yeniBirDizi > 24]

array([73, 95, 44, 26, 93, 49, 84, 35, 49, 25, 55, 39])

In [48]:
sonDizi = np.arange(0,24)

In [49]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [51]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [53]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [54]:
sonDizi / sonDizi

C:\Users\Özkan\AppData\Local\Temp\ipykernel_17628\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [56]:
np.max(sonDizi)

23

In [57]:
np.min(sonDizi)

0